# Generated by Django 5.0.7 on 2024-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_review_bookname_review_book_alter_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
