# Generated by Django 5.0.7 on 2024-07-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
